### ISSUE TITLE
Easy way to have page-images in my engine

### ISSUE THREAD

**Issue by prokopsimek** [refinery/refinerycms-page-images#111]
Hi, I would like to have page-images in my generated engine... What is the best way to add page-images to my admin form?

My page-images.rb initializer:
```ruby
Refinery::PageImages.configure do |config|
  # config.captions = false
  config.enable_for = [{:model=>"Refinery::Page", :tab=>"Refinery::Pages::Tab"}, {:model=>"Refinery::Stories::Story", :tab=>"Refinery::Stories::Story::Tab"}]
  # config.wysiwyg = true
end

```
My admin form:
```erb
<%= form_for [refinery, :stories_admin, @story] do |f| -%>
  <%= render '/refinery/admin/error_messages',
              :object => @story,
              :include_object_name => true %>

  <%= render '/refinery/admin/locale_picker',
              :current_locale => Globalize.locale %>
  <div class='field'>
    <%= f.label :title -%>
    <%= f.text_field :title, :class => 'larger widest' -%>
  </div>

  <div class='field'>
    <%= render '/refinery/admin/wysiwyg',
                :f => f,
                :fields => [:short_description, :long_description],
                :object => "stories/story" -%>
  </div>

  <%= render '/refinery/admin/form_actions', :f => f,
             :continue_editing => false,
             :delete_title => t('delete', :scope => 'refinery.stories.admin.stories.story'),
             :delete_confirmation => t('message', :scope => 'refinery.admin.delete', :title => @story.title) -%>
<% end -%>

<% content_for :javascripts do -%>
  <script>
    $(document).ready(function(){
      page_options.init(false, '', '');
    });
  </script>
<% end -%>
```

I would like to add it with nice way... Not like this e.g.:
https://github.com/refinery/refinerycms-blog/blob/master/app/views/refinery/blog/admin/posts/_form.html.erb#L23
or
https://github.com/refinery/refinerycms/blob/master/pages/app/views/refinery/admin/pages/_form_page_parts.html.erb#L33

Could I make it easier?
Like e.g.:
```erb
<%= render '/refinery/admin/wysiwyg',
                :f => f,
                :fields => [:short_description, :long_description, :page_images],
                :object => "stories/story" -%>
```

Thx

**Comment by LyriD** [comment]
thx!

**Comment by natebeaty** [comment]
This sure would be ideal:

        <%= render '/refinery/admin/wysiwyg',
                :f => f,
                :fields => [:description, :details, :page_images],
                :object => "products/product" -%>

And then just adding the initializer and `has_many_page_images`.

Ironically it was much easier in Refinery 1.0 to add page_images to engines.

**Comment by slavajacobson** [comment]
No guide/solution for this?

**Comment by oolzpishere** [comment]
In rails 4.2 need to add permit for write to database
/vendor/extensions/galleries/app/controllers/refinery/galleries/admin/galleries_controller.rb
```
params.require(:gallery).permit(:images_attributes => [:id, :caption, :image_page_id])
````

**Comment by bricesanchez** [comment]
@oolzpishere It's written in this guide : http://www.refinerycms.com/guides/adding-an-image-collection-to-an-extension-using-pageimages but i seen it needs formatting
