### ISSUE TITLE
Friendly_id version

### ISSUE THREAD

**Issue by IvanVP** [refinery/refinerycms-page-images#118]
Hello.
When I run bundle update, I see error ->
```
Bundler could not find compatible versions for gem "friendly_id":
  In Gemfile:
    refinerycms-page-images (>= 0) ruby depends on
      friendly_id (~> 5.0.1) ruby

    refinerycms (>= 0) ruby depends on
      friendly_id (5.1.0)
```

Can You correct this?

**Comment by parndt** [comment]
This extension doesn't directly depend on friendly_id so I'm not sure what's causing that dependency exactly, or why it's then saying that refinerycms requires 5.1.0 which isn't the case as far as I'm aware.. I can't find that in the codebase anywhere.

**Comment by parndt** [comment]
Actually, it's a transitive dependency from refinerycms-pages which is specifying `~> 5.0.1` but I don't know where `5.1.0` is coming from.

**Comment by IvanVP** [comment]
I'm sorry. 5.1.0 is coming directly from Rubygems. Thank You.
