### ISSUE TITLE
NoMethodError: private method `prepend' 

### ISSUE THREAD

**Issue by pekakate** [refinery/refinerycms-page-images#138]
Hi, I can't solve it:
NoMethodError: private method `prepend' called for Refinery::Admin::PagesController:Class
/app/decorators/controllers/refinery/admin/pages_controller_decorator.rb:1:in`<top (required)>'

I tried this: 
Refinery::Blog::Admin::PostsController.send :prepend, MODULE CODE
instead the original Refinery::Blog::Admin::PostsController.prepend(

but I have the same error at heroku run rake db:migrate

and the app crashed and not available :(

**Comment by pekakate** [comment]
I did with blogpost and pages decorator too:
`Refinery::Admin::PagesController.send :prepend,
  Module.new do`
`Refinery::Blog::Admin::PostsController.send :prepend, MODULE CODE`

I've got the same rake aborted:

rake aborted!
NoMethodError: private method `prepend' called for Refinery::Admin::PagesController:Class
/app/vendor/bundle/ruby/2.0.0/bundler/gems/refinerycms-page-images-ed35b79283cc/app/decorators/controllers/refinery/admin/pages_controller_decorator.rb:1:in `<top (required)>'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
/app/vendor/bundle/ruby/2.0.0/gems/decorators-2.0.1/lib/decorators.rb:8:in `block in load!'
/app/vendor/bundle/ruby/2.0.0/gems/decorators-2.0.1/lib/decorators.rb:6:in `each'
/app/vendor/bundle/ruby/2.0.0/gems/decorators-2.0.1/lib/decorators.rb:6:in `load!'
/app/vendor/bundle/ruby/2.0.0/gems/decorators-2.0.1/lib/decorators/railtie.rb:7:in `block (2 levels) in <class:Railtie>'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/lazy_load_hooks.rb:36:in `call'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/lazy_load_hooks.rb:44:in `each'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
/app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
/app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `instance_exec'
/app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `run'
/app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/initializable.rb:55:in `block in run_initializers'
/app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/initializable.rb:44:in `each'
/app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/initializable.rb:44:in `tsort_each_child'
/app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/initializable.rb:44:in `each'
/app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/initializable.rb:44:in `tsort_each_child'
/app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/initializable.rb:54:in `run_initializers'
/app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/application.rb:352:in `initialize!'
/app/config/environment.rb:5:in `<top (required)>'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
/app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/application.rb:328:in `require_environment!'
/app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/application.rb:457:in `block in run_tasks_blocks'
Tasks: TOP => db:migrate => environment

**Comment by bricesanchez** [comment]
Hello,

We need more informations to be able to fix the problem such as :
*  Could you copy/paste your Gemfile.lock ?
*  Do you have a step by step to reproduce?

Thanks!

**Comment by bricesanchez** [comment]
I close it due to inactivity
