### ISSUE TITLE
refinerycms-page-images 

### ISSUE THREAD

**Issue by michael-sd** [refinery/refinerycms-page-images#147]
Hey guys,

I'm implementing refinery-page-images within an existing rails app.
The rails version is 5.1

The gem I'm using to add refinery is:
`gem 'refinerycms', '~> 4.0.0'`

I'm using the latest version of refinerycms-page-images:
`gem 'refinerycms-page-images', '~> 3.0.0', github: "refinery/refinerycms-page-images", branch: "master"`

Upon bundle install I'm getting this:
`Bundler could not find compatible versions for gem "refinerycms-pages":
  In snapshot (Gemfile.lock):
    refinerycms-pages (= 4.0.0)`

  `In Gemfile:
    refinerycms (~> 4.0.0) was resolved to 4.0.0, which depends on
      refinerycms-pages (= 4.0.0)`

   ` refinerycms-page-images (~> 3.0.0) was resolved to 3.0.0, which depends on
      refinerycms-pages (~> 3.0.0)`

`Running bundle update will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.`

Upon bundle update, I'm then getting this:
`Bundler could not find compatible versions for gem "refinerycms-pages":
  In Gemfile:
    refinerycms (~> 4.0.0) was resolved to 4.0.0, which depends on
      refinerycms-pages (= 4.0.0)`

    refinerycms-page-images (~> 3.0.0) was resolved to 3.0.0, which depends on
      refinerycms-pages (~> 3.0.0)`

Do you guys know of a fix/work around for this?

Many thanks in advance.

**Comment by bricesanchez** [comment]
Hi !

`refinerycms-page-images` is not yet compatible with `refinerycms` 4.0.

Could you test this PR and report any bug? 

#148

**Comment by michael-sd** [comment]
@bricesanchez, sure no worries, I'll report back accordingly.
