### ISSUE TITLE
heroku pre-compiling assets now fails

### ISSUE THREAD

**Issue by andrewhavens** [refinery/refinerycms-page-images#69]
So now that I've added the refinerycms-page-images gem and deploy to heroku, when it goes to pre-compile the assets to add to the slug, it fails with the message:

```
Running: rake assets:precompile
   rake aborted!
   could not connect to server: Connection refused
   Is the server running on host "127.0.0.1" and accepting
   TCP/IP connections on port 5432?
```

I am running Rails 3.2.6 and refinerycms/refinerycms-page-images '~> 2.0.0'

I found some articles online which say they solved the issue by adding this line to their config/application.rb file:

```
config.assets.initialize_on_precompile = false
```

But that resulted in a different error for me:

```
   Running: rake assets:precompile
   rake aborted!
   undefined method `admin_dialogs_path' for #<Module:0x00000005d92da8>
   (in /tmp/build_2lptj1tk77zwu/vendor/bundle/ruby/1.9.1/gems/refinerycms-core-2.0.5/app/assets/javascripts/refinery/boot_wym.js.erb)
   Tasks: TOP => assets:precompile:primary
   (See full trace by running task with --trace)
   Precompiling assets failed, enabling runtime asset compilation
```

Now I dont know what to do to fix this. What should I do?

**Comment by LoganDSPrice** [comment]
@parndt How is this issue fixed now that Heroku has deprecated user-env-compile?

**Comment by parndt** [comment]
@LoganDSPrice have you encountered the issue?
