### ISSUE TITLE
Cannot reorder pages

### ISSUE THREAD

**Issue by olhor** [refinery/refinerycms-page-images#95]
I'm getting an error while trying to reorder pages from refinery backend:

```
SystemStackError (stack level too deep):
  actionpack (3.2.16) lib/action_dispatch/middleware/reloader.rb:70
```

I'm using refinery 2.1.1 with 'refinerycms-page-images (2.1.0)'. I tested this behaviour on sqlite and postgresql databases with rails 3.2.16 and ruby 1.9.3.

It can be easily reproduced:
1. Add  gem 'refinerycms-page-images', '~> 2.1.0' to Gemfile
2. run bundle
3. Open 'Pages' tab in the backend
4. Try to reorder the pages

**Comment by bricesanchez** [comment]
If this issue happens in the Images tab of pages i can't reproduce it, so it's fixed for me. Thanks.
